import { prisma } from "@/prisma/client";
import { getHumanRuntimeConfig, HumanAction } from "@/utilities/human/config";
import { TrustTier } from "@/utilities/human/trust";

export type AuthenticityDecision = "allow" | "pending_review" | "block";

type EvaluateRiskInput = {
    text?: string | null;
    hasMedia?: boolean;
    challengePresent: boolean;
    challengeScore?: number | null;
    trustScore: number;
    trustTier: TrustTier;
};

const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));

const containsSyntheticSignal = (text: string) => {
    const normalized = text.toLowerCase();
    const markers = [
        "as an ai",
        "generated by",
        "chatgpt",
        "midjourney",
        "stable diffusion",
        "prompt",
        "llm",
    ];

    return markers.some((marker) => normalized.includes(marker));
};

export const evaluateAuthenticityRisk = (input: EvaluateRiskInput) => {
    const { reviewThreshold, blockThreshold } = getHumanRuntimeConfig();

    const normalizedText = (input.text || "").trim();

    let risk = 0.4;
    const reasons: string[] = [];

    risk -= input.trustScore * 0.35;

    if (!input.challengePresent) {
        risk += 0.35;
        reasons.push("challenge_missing");
    }

    if (typeof input.challengeScore === "number") {
        if (input.challengeScore < 0.5) {
            risk += 0.15;
            reasons.push("challenge_low_score");
        } else {
            risk -= 0.08;
        }
    }

    if (input.hasMedia) {
        risk += 0.06;
        reasons.push("contains_media");
    }

    if (normalizedText.length > 220) {
        risk += 0.04;
        reasons.push("long_text");
    }

    if (normalizedText && containsSyntheticSignal(normalizedText)) {
        risk += 0.2;
        reasons.push("synthetic_keywords");
    }

    if (input.trustTier === "new") {
        risk += 0.08;
        reasons.push("new_account_tier");
    }

    const score = Number(clamp(risk).toFixed(4));

    let suggestedDecision: AuthenticityDecision = "allow";
    if (score >= blockThreshold) suggestedDecision = "block";
    else if (score >= reviewThreshold) suggestedDecision = "pending_review";

    return {
        score,
        reasons,
        suggestedDecision,
    };
};

export const persistAuthenticityCheck = async ({
    actorId,
    action,
    text,
    hasMedia,
    challengeSessionId,
    challengeScore,
    riskScore,
    trustTier,
    trustScore,
    suggestedDecision,
    ruleVersion,
    metadata,
    tweetId,
    mediaAssetId,
}: {
    actorId: string;
    action: HumanAction;
    text?: string | null;
    hasMedia?: boolean;
    challengeSessionId?: string | null;
    challengeScore?: number | null;
    riskScore: number;
    trustTier: TrustTier;
    trustScore: number;
    suggestedDecision: AuthenticityDecision;
    ruleVersion?: string | null;
    metadata?: Record<string, unknown>;
    tweetId?: string | null;
    mediaAssetId?: string | null;
}) => {
    const { dryRun } = getHumanRuntimeConfig();

    const status = suggestedDecision === "allow" ? "resolved" : "open";

    return prisma.authenticityCheck.create({
        data: {
            actorId,
            action,
            subjectType: hasMedia ? "media" : "tweet",
            status,
            decision: suggestedDecision,
            score: riskScore,
            challengeScore: challengeScore ?? null,
            trustedTier: trustTier,
            ruleVersion: ruleVersion || null,
            modelVersion: "human-risk-v1",
            reasons: {
                dryRun,
                hasMedia: Boolean(hasMedia),
                decision: suggestedDecision,
            },
            contentText: text ? text.slice(0, 280) : null,
            metadata: {
                ...(metadata || {}),
                trustScore,
                dryRun,
            },
            challengeSessionId: challengeSessionId || null,
            tweetId: tweetId || null,
            mediaAssetId: mediaAssetId || null,
            reviewedAt: suggestedDecision === "allow" ? new Date() : null,
        },
    });
};
